# This file contains copyright info for data files in the project directory.
# It is shipped with our sdist packages, although not all members are actually included.

# Note, this file has been auto-converted from .reuse/dep5 by `reuse convert-dep5`

version = 1
SPDX-PackageName = "pypdfium2"
SPDX-PackageSupplier = "geisserml <geisserml@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/pypdfium2-team/pypdfium2"

[[annotations]]
path = [
    "req/*.txt",
    "autorelease/record.json",
    "autorelease/config.json",
    ".github/PULL_REQUEST_TEMPLATE.md",
    "tests/expectations/*.txt",
    "tests/resources/render.pdf",
    "tests/resources/multipage.pdf",
    "tests/resources/encrypted.pdf",
    "tests/resources/text.pdf",
    "tests/resources/empty.pdf",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 geisserml <geisserml@gmail.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "autorelease/bindings.py"
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2026 ctypesgen developers",
    "2026 geisserml <geisserml@gmail.com>",
]
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Auto-generated by ctypesgen. Probably not copyrighted."

[[annotations]]
path = "tests/resources/toc.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Matthias Erll"
SPDX-License-Identifier = "MPL-2.0"
SPDX-FileComment = '''
Obtained from https://github.com/pikepdf/pikepdf/blob/master/tests/resources/outlines.pdf
pikepdf's REUSE.toml says "License assumed from LICENSE.txt in project root.":
https://github.com/pikepdf/pikepdf/blob/2662d9da649a3b354422673fb62bcfe0a1b9ba4c/REUSE.toml#L154
'''

[[annotations]]
path = [
    "tests/resources/toc_circular.pdf",
    "tests/resources/toc_viewmodes.pdf",
    "tests/resources/toc_maxdepth.pdf",
    "tests/resources/forms.pdf",
    "tests/resources/attachments.pdf",
    "tests/resources/mona_lisa.jpg",
    "tests/resources/form_object_with_image.pdf",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 PDFium developers"
SPDX-License-Identifier = "BSD-3-Clause AND Apache-2.0"
SPDX-FileComment = '''
Test files obtained from pdfium's //testing/resources or the pdfium_tests corpus:
https://pdfium.googlesource.com/pdfium/+/refs/heads/main/testing/resources/bookmarks_circular.pdf
https://pdfium.googlesource.com/pdfium_tests/+/refs/heads/main/fx/other/8.2_outline.pdf
https://pdfium.googlesource.com/pdfium_tests/+/refs/heads/main/fx/FRC_8.2.2_part1/FRC_51_8.2.2_T_8.4__Count_edit_count_100.pdf
https://pdfium.googlesource.com/pdfium/+/refs/heads/main/testing/resources/listbox_form.pdf
https://pdfium.googlesource.com/pdfium/+/refs/heads/main/testing/resources/embedded_attachments.pdf
https://pdfium.googlesource.com/pdfium/+/refs/heads/main/testing/resources/mona_lisa.jpg
https://pdfium.googlesource.com/pdfium/+/refs/heads/main/testing/resources/form_object_with_image.pdf

pdfium's LICENSE file includes both BSD-3-Clause and Apache-2.0 texts
We're not sure if this meant as SPDX "AND" or "OR", so use the conservative (safe) assumption "AND".
'''

[[annotations]]
path = [
    "tests/resources/box_fallback.in",
    "tests/resources/box_fallback.pdf",
]
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2022 PDFium developers",
    "2026 geisserml <geisserml@gmail.com>",
]
SPDX-License-Identifier = "BSD-3-Clause AND Apache-2.0"
SPDX-FileComment = "See above regarding pdfium's double-license."

[[annotations]]
path = "tests/resources/images.pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2022 Johannes Schauer Marin Rodrigues <josch@mister-muffin.de>",
    "2026 geisserml <geisserml@gmail.com>",
]
SPDX-License-Identifier = "LGPL-3.0-or-later"
SPDX-FileComment = '''
Obtained from img2pdf. No individual license stated for this data file.
'''

[[annotations]]
path = [
    "patches/win/use_resources_rc.patch",
    "patches/win/build.patch",
    "patches/win/resources.rc",
    "patches/android_crossbuild.patch"
]
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2026 Beno√Æt Blanchon and pdfium-binaries contributors",
    "2026 geisserml",
]
SPDX-License-Identifier = "MIT"
SPDX-FileComment = '''
Derived from https://github.com/bblanchon/pdfium-binaries/tree/master/patches
See also //BUILD_LICENSES/pdfium-binaries.txt for a copy of upstream's license file as embedded in the tarballs.
'''

[[annotations]]
path = [
    "patches/ffp_contract.patch",
    "patches/avoid_new_clang_flags.patch",
    "patches/system_libcxx_with_clang.patch",
    "patches/legacy_gn.patch",
    "patches/android_build.patch",
    "patches/gn_build.patch",
    "patches/no_libclang_rt.patch",
    "patches/win/arm64_native.patch",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 geisserml <geisserml@gmail.com>"
SPDX-License-Identifier = "BSD-3-Clause OR Apache-2.0"

[[annotations]]
path = "patches/legacy_libs_compat.patch"
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2025 wojiushixiaobai <296015668@qq.com>",
    "2026 geisserml <geisserml@gmail.com>",
]
SPDX-License-Identifier = "BSD-3-Clause OR Apache-2.0"

[[annotations]]
path = [
    "patches/bigendian.patch",
    "patches/bigendian_test.patch",
]
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2025 Christian Heimes <cheimes@redhat.com>",
    "2026 geisserml <geisserml@gmail.com>",
]
SPDX-License-Identifier = "LicenseRef-Ignore"
SPDX-FileComment = '''
Derived from RedHat packaging repository: https://github.com/tiran/libpdfium/blob/d99370b3ac7f0c9cd7222be2dfab2c7b648f2e9e/0001-bigendian.patch
Repo does not have an own license file, but assumably the patches are being made available under pdfium's license, or leastways an open-source license.
'''

[[annotations]]
path = "patches/abseil_ppc64le_musl.patch"
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 The abseil authors"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = '''
Cherry-pick https://github.com/abseil/abseil-cpp/commit/8e7767542cfde43f16c142f05dce06cadb7f7f84
'''

[[annotations]]
path = [
    "docs/build/.gitkeep",
    "sbuild/.gitkeep",
    "RELEASE.md",  # TODO add to gitignore?
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 geisserml"
SPDX-License-Identifier = "CC-BY-4.0"
SPDX-FileComment = "Other files"

[[annotations]]
path = ["BUILD_LICENSES/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "unknown"
SPDX-License-Identifier = "LicenseRef-Ignore"
SPDX-FileComment = "Licenses for compiled binaries of pdfium."
