# SPDX-FileCopyrightText: 2026 geisserml <geisserml@gmail.com>
# SPDX-License-Identifier: CC-BY-4.0

blank_issues_enabled: false
contact_links:
  - name: pypdfium2 discussions
    url: https://github.com/pypdfium2-team/pypdfium2/discussions
    about: pypdfium2 community support
  - name: PDFium mailing list
    url: https://groups.google.com/g/pdfium/
    about: PDFium community support
